plugins {
    id 'org.springframework.boot'
}

bootJar {
    archiveFileName = 'app.jar'
}

dependencies {
    implementation project(':common')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.micrometer:micrometer-registry-prometheus'
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'
    implementation 'org.springframework.cloud:spring-cloud-gateway-server-mvc'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
