apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    # Docker Compose 服務名（同 network）
    url: http://prometheus:9090
    isDefault: true
    editable: false
